// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/uto-studio/Editorial.tsx": () => import("../components/mockups/uto-studio/Editorial.tsx"),
  "./components/mockups/uto-studio/StudioCalm.tsx": () => import("../components/mockups/uto-studio/StudioCalm.tsx")
};
